name: kheticonnect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  localization: ^2.1.0

  # util
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  photo_view: ^0.15.0
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/drawables/
    - assets/languages/

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/ExoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/ExoRomanSemiBold.ttf
          weight: 600
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
